attach(calories_consumed)
View(calories_consumed)
summary(calories_consumed)
hist(Calories.Consumed)
hist(Weight.gained..grams.)
library(moments)
skewness(Calories.Consumed)
kurtosis(Calories.Consumed)
plot(Calories.Consumed,Weight.gained..grams.)
cor(Calories.Consumed,Weight.gained..grams.)
library(e1071)
slrcc=lm(Weight.gained..grams.~Calories.Consumed,data=calories_consumed)
summary(slrcc)
confint(slrcc,level = 0.95)
predict(slrcc,interval = "predict")
slrcc1=lm(log(Weight.gained..grams.)~Calories.Consumed,data=calories_consumed)
summary(slrcc1)
confint(slrcc1,level=0.95)
predict(slrcc1,interval = "predict")
exp(slrcc1$fitted.values)
