attach(delivery_time)
View(delivery_time)
summary(delivery_time)
library(moments)
skewness(delivery_time)
hist(Sorting.Time)
plot(delivery_time)
cor(Sorting.Time,Delivery.Time)  
slrdt=lm(Delivery.Time~Sorting.Time)
summary(slrdt)
confint(slrdt,level = 0.95)
predict(slrdt,interval = "predict")
slrdt1=lm(Delivery.Time~log(Sorting.Time))
summary(slrdt1)
confint(slrdt1,level = 0.95)
predict(slrdt1,interval = "predict")
slrdt2=lm(log(Delivery.Time)~Sorting.Time)
summary(slrdt2)
confint(slrdt2,level = 0.95)
predict(slrdt2,interval = "predict")
exp(slrdt2$fitted.values)
slrdt3=lm(sqrt(Delivery.Time)~Sorting.Time)
summary(slrdt3)
confint(slrdt3,level = 0.95)
predict(slrdt3,interval = "predict")
slrdt3$fitted.values^2
slrdt4=lm(Delivery.Time~sqrt(Sorting.Time))
summary(slrdt4)
confint(slrdt4,level = 0.95)
predict(slrdt4,interval = "predict")
slrdt5=lm(1/(Delivery.Time)~Sorting.Time)
summary(slrdt5)
confint(slrdt5,level = 0.95)
predict(slrdt5,interval = "predict")
1/slrdt5$fitted.values
#The model with the most R squared value is slrdt2 that is with log(Y).
