attach(emp_data)
View(emp_data)
summary(emp_data)
hist(Salary_hike)
library(moments)
skewness(Salary_hike)
plot(Salary_hike,Churn_out_rate)
cor(Salary_hike,Churn_out_rate)
slr_ed=lm(Churn_out_rate~Salary_hike)
summary(slr_ed)
confint(slr_ed,level=0.95)
predict(slr_ed,interval = "predict")
slr_ed1=lm(Churn_out_rate~log(Salary_hike))
summary(slr_ed1)
confint(slr_ed1,level=0.95)
predict(slr_ed1,interval = "predict")
slr_ed2=lm(log(Churn_out_rate)~Salary_hike)
summary(slr_ed2)
confint(slr_ed2,level=0.95)
predict(slr_ed2,interval = "predict")
exp(slr_ed2$fitted.values)
slr_ed3=lm(Churn_out_rate~sqrt(Salary_hike))
summary(slr_ed3)
confint(slr_ed3,level=0.95)
predict(slr_ed3,interval = "predict")
slr_ed4=lm(sqrt(Churn_out_rate)~Salary_hike)
summary(slr_ed4)
confint(slr_ed4,level=0.95)
predict(slr_ed4,interval = "predict")
slr_ed2$fitted.values^2
#The model with the best R squared value is slr_ed2 that has log(Y). 